
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victoralonso
 */
public class Board extends javax.swing.JPanel {
    
    private Snake snake;
    private Food food;
    private Food specialFood;
    private Timer snakeTimer;
    private Timer specialFoodTimer;
    private int deltaTime;
    public  int numRows = 15;
    public  int numCols = 15;
    private final int INITIAL_DELTA_TIME = 300;
    private ScoreBoard scoreBoard;
    
    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        myInit();
    }

    public void setScoreBoard(ScoreBoard scoreBoard) {
        this.scoreBoard = scoreBoard;
    }
    
    
    
    private void myInit() {
        
        snake = new Snake(5, 5, 3, this);
        food = new Food(snake, this);
        
        deltaTime = INITIAL_DELTA_TIME;
       
        
        createTimer();
        
        MyKeyAdapter keyAdepter = new MyKeyAdapter();
        addKeyListener(keyAdepter);
        setFocusable(true);
    }
    
    public Board(int numRows, int numCols) {
        
        initComponents();
        myInit();
        this.numRows = numRows;
        this.numCols = numCols;
                
    }
    
    public boolean colideFood(int row, int col) {
        
        Node node = food.getPosition();
        
        if (row == node.getRow() && col == node.getCol()) {
            foodEat();
            return true;
        }
        
        return false;
    }
    
    private void foodEat() {
        food.generateFood(snake);
        if(deltaTime > 100) {
            deltaTime -= 20;
        }
        scoreBoard.incrementScore(10);
        createTimer();
    }
    
    public int squareWidth() {
        return (int) Math.floor(getWidth()/numCols);
    }
    
    public int squareHeight() {
        return (int) Math.floor(getHeight()/numRows);
    }
    
    public void gameOver() {
        
        int gameOver = JOptionPane.showConfirmDialog(this, "Game Over, wanna play again?", "Game over", 0);
        
        if (gameOver == 0) {
            restart();
        } else {
            snakeTimer.stop();
        }
        
    }
    
    @Override 
    protected void paintComponent(Graphics g)  {
       
        super.paintComponent(g);
        
        
        snake.paint(g);
        food.paint(g);
        
    }
    
    
    private void restart() {
        
        snake = new Snake(5, 5, 3, this);
        food.generateFood(snake);
        deltaTime = INITIAL_DELTA_TIME;
        scoreBoard.resetScore();
        
    }
    
    
    class MyKeyAdapter extends KeyAdapter {

        @Override
        public void keyPressed(KeyEvent e) {
            switch (e.getKeyCode()) {
                case KeyEvent.VK_UP:
                    snake.setDirection(Direction.UP);
                    break;
                case KeyEvent.VK_RIGHT:
                    snake.setDirection(Direction.RIGHT);
                    break;
                case KeyEvent.VK_DOWN:
                    snake.setDirection(Direction.DOWN);
                    break;
                case KeyEvent.VK_LEFT:
                   snake.setDirection(Direction.LEFT);
                    break;
                
            }
        }
    }
    
     private void createTimer() {
       if (snakeTimer != null) {
           snakeTimer.stop();
       }
        snakeTimer = new Timer(deltaTime, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
               
                snake.move();
                repaint();
                
                
            }

           

        });
        snakeTimer.start();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

